# Generated by Django 4.0.4 on 2022-04-25 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='updated_at',
        ),
    ]
